[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#29ABE2"
backgroundColor = "#0B141C"
secondaryBackgroundColor = "#113244"
textColor = "#FFFFFF"
linkColor = "#29ABE2"
borderColor = "#164961"

[theme.sidebar]
backgroundColor = "#0B141C"
secondaryBackgroundColor = "#113244"
borderColor = "#164961"
